name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: create env file
        run: |
          touch .env
          echo GOOGLE_SA_CLIENT_EMAIL=${{ secrets.GOOGLE_SA_CLIENT_EMAIL }} >> .env
          echo GOOGLE_SA_PROJECT_ID=${{ secrets.GOOGLE_SA_PROJECT_ID }} >> .env
          echo GOOGLE_SA_PRIVATE_KEY=${{ secrets.GOOGLE_SA_PRIVATE_KEY }} >> .env
          echo BUCKET_URL=${{ secrets.BUCKET_URL }} >> .env
          echo ENV=${{ secrets.ENV }} >> .env
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
